import { writeFile } from "node:fs/promises";
const headers = {
  Accept: "application/vnd.github+json",
  "User-Agent": "AngelFerMota-portfolio",
};
if (process.env.GITHUB_TOKEN)
  headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
async function get(path) {
  const response = await fetch(`https://api.github.com/${path}`, {
    headers,
    signal: AbortSignal.timeout(15000),
  });
  if (!response.ok) throw new Error(`GitHub returned ${response.status}`);
  return response.json();
}
// Only public repositories are requested; authentication stays in the build process.
const repositories = await get(
  "users/AngelFerMota/repos?type=owner&per_page=100",
);
const selected = [
  "Reddit-Brief",
  "ToDoTareas-Angular-.NET",
  "TuCompra.Kcal",
  "flutter_weather_app",
];
const projects = await Promise.all(
  selected.map(async (name) => {
    const repo = repositories.find((item) => item.name === name);
    if (!repo) throw new Error(`Missing public repository ${name}`);
    const commits = await get(`repos/AngelFerMota/${name}/commits?per_page=1`);
    return {
      repo: name,
      language: repo.language,
      stars: repo.stargazers_count,
      lastCommit: commits[0].commit.committer.date.slice(0, 10),
    };
  }),
);
const snapshot = {
  updated: new Date().toISOString().slice(0, 10),
  repositories: repositories.length,
  projects,
};
await writeFile(
  "src/app/github-snapshot.ts",
  `// Generated by npm run sync:github; public data only.\nexport const githubSnapshot = ${JSON.stringify(snapshot, null, 2)} as const;\n`,
);
console.log(
  `Updated public GitHub snapshot: ${snapshot.repositories} repositories, ${projects.length} cases.`,
);
